# Generated by Django 6.1.1 on 2026-10-04 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='bio_paragraph_1',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='bio_paragraph_2',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='bio_paragraph_3',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='bio_paragraph_4',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='education_institution',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='education_title',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='education_years',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='greeting',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='homesection',
            name='resume_file',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='bio_p1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='bio_p2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='no-email@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homesection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homesection',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='EducationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('years', models.CharField(max_length=100)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='api.aboutsection')),
            ],
        ),
    ]
