# Generated by Django 4.2.30 on 2026-10-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_aboutsection_id_alter_contactinfo_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationitem',
            name='cgpa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='educationitem',
            name='percentage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='educationitem',
            name='pursuing',
            field=models.BooleanField(default=False),
        ),
    ]
